POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre":"Óscar J",
    "apellido":"González",
    "correo":"t3@t.com",
    "url": "https://randomuser.me/api/portraits/men/8.jpg",
    "sexo":"H",
    "fecha":"1994-03-19",
    "password":"123456"
}

###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "correo":"t3@t.com",
    "password":"123456"
}

###

GET http://localhost:3000/api/products
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiLDk3NjYXIgSiIsImlkIjoiNWZhZDQ2MjUwNzVlMjIyMjQ4ODk4YmJkIiwiaWF0IjoxNjA1NzU1MDAwfQ.WnAtNJS0_lquXbE0gh7_lvdEcq-d39Qmt9dXoOPm2h8